#-------------------------------
# General Site Settings
title: Vasco Neves
description: "Hello! I'm Vasco, Data Scientist.  My portfolio showcases example projects I've recently undertaken, with a strong emphasis on business impact. Please visit my Github & LinkedIn pages by using the links below or download my Resume for further details!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Earth"
resume_url: "docs/Vasco_Neves_CV_v12DS.pdf"
avatar_image: /img/profile_picture.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/vasco-neves-ph-d-5544441a/" # Add your linkedln handle
github: "https://github.com/vasconeves/"  # Add your github handle

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 20
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: true


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
